Repository kubedb/apimachinery, pull requests merged in 2018-08, with the labels that each got.

#248 Added tls field and update monitoring path in etcd
  api/openapi-spec/swagger.json
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/etcd_types.go
  apis/kubedb/v1alpha1/openapi_generated.go
Labels: in progress

#249 Revise crd spec
  api/openapi-spec/swagger.json
  apis/kubedb/v1alpha1/crds.yaml
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_types.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/etcd_types.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/memcached_types.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mongodb_types.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/mysql_types.go
  apis/kubedb/v1alpha1/openapi_generated.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/postgres_types.go
  apis/kubedb/v1alpha1/redis_helpers.go
  apis/kubedb/v1alpha1/redis_types.go
  apis/kubedb/v1alpha1/snapshot_types.go
  apis/kubedb/v1alpha1/types.go
  apis/kubedb/v1alpha1/zz_generated.deepcopy.go
  glide.lock
  glide.yaml
  hack/codegen.sh
  pkg/admission/snapshot/admission_test.go
  pkg/controller/snapshot/cron.go
  pkg/validator/validate.go
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_linux.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/kmodules.xyz/monitoring-agent-api/api/doc.go
  vendor/kmodules.xyz/monitoring-agent-api/api/v1/doc.go
  vendor/kmodules.xyz/monitoring-agent-api/api/v1/openapi_generated.go
  vendor/kmodules.xyz/monitoring-agent-api/api/v1/types.go
  vendor/kmodules.xyz/monitoring-agent-api/api/v1/zz_generated.deepcopy.go
  vendor/kmodules.xyz/objectstore-api/api/doc.go
  vendor/kmodules.xyz/objectstore-api/api/v1/doc.go
  vendor/kmodules.xyz/objectstore-api/api/v1/helpers.go
  vendor/kmodules.xyz/objectstore-api/api/v1/openapi_generated.go
  vendor/kmodules.xyz/objectstore-api/api/v1/types.go
  vendor/kmodules.xyz/objectstore-api/api/v1/zz_generated.deepcopy.go
  vendor/kmodules.xyz/objectstore-api/osm/osm.go
  vendor/kmodules.xyz/offshoot-api/LICENSE
  vendor/kmodules.xyz/offshoot-api/api/v1/doc.go
  vendor/kmodules.xyz/offshoot-api/api/v1/openapi_generated.go
  vendor/kmodules.xyz/offshoot-api/api/v1/types.go
  vendor/kmodules.xyz/offshoot-api/api/v1/zz_generated.deepcopy.go
Labels: in progress

#252 Revise optional fields
  api/openapi-spec/swagger.json
  apis/kubedb/v1alpha1/crds.yaml
  apis/kubedb/v1alpha1/elasticsearch_types.go
  apis/kubedb/v1alpha1/etcd_types.go
  apis/kubedb/v1alpha1/memcached_types.go
  apis/kubedb/v1alpha1/mongodb_types.go
  apis/kubedb/v1alpha1/mysql_types.go
  apis/kubedb/v1alpha1/openapi_generated.go
  apis/kubedb/v1alpha1/postgres_types.go
  apis/kubedb/v1alpha1/postgres_version_types.go
  apis/kubedb/v1alpha1/redis_types.go
  apis/kubedb/v1alpha1/snapshot_types.go
  apis/kubedb/v1alpha1/types.go
  apis/kubedb/v1alpha1/zz_generated.deepcopy.go
  glide.lock
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_linux.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/kmodules.xyz/offshoot-api/api/v1/types.go
  vendor/kmodules.xyz/offshoot-api/api/v1/zz_generated.deepcopy.go
Labels: in progress

#253 Fix ES podTemplate
  api/openapi-spec/swagger.json
  apis/kubedb/v1alpha1/crds.yaml
  apis/kubedb/v1alpha1/elasticsearch_types.go
  apis/kubedb/v1alpha1/openapi_generated.go
  apis/kubedb/v1alpha1/zz_generated.deepcopy.go
Labels: in progress

#255 Move crds to api folder
  api/crds/dormantdatabase.yaml
  api/crds/elasticsearch.yaml
  api/crds/memcached.yaml
  api/crds/mongodb.yaml
  api/crds/mysql.yaml
  api/crds/postgres.yaml
  api/crds/postgresversion.yaml
  api/crds/redis.yaml
  api/crds/snapshot.yaml
  api/openapi-spec/swagger.json
  apis/kubedb/v1alpha1/crds.yaml
  hack/gencrd/main.go
Labels: in progress

#257 Update offshoot api
  api/crds/elasticsearch.yaml
  api/crds/memcached.yaml
  api/crds/mongodb.yaml
  api/crds/mysql.yaml
  api/crds/postgres.yaml
  api/crds/redis.yaml
  api/crds/snapshot.yaml
  api/openapi-spec/swagger.json
  apis/kubedb/v1alpha1/openapi_generated.go
  glide.lock
  vendor/github.com/appscode/kutil/util.go
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_linux.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/kmodules.xyz/offshoot-api/api/v1/openapi_generated.go
  vendor/kmodules.xyz/offshoot-api/api/v1/types.go
  vendor/kmodules.xyz/offshoot-api/api/v1/zz_generated.deepcopy.go
Labels: in progress

#256 Add <DB>Version types
  api/crds/elasticsearchversion.yaml
  api/crds/memcachedversion.yaml
  api/crds/mongodbversion.yaml
  api/crds/mysqlversion.yaml
  api/crds/redisversion.yaml
  api/openapi-spec/swagger.json
  apis/kubedb/v1alpha1/elasticsearch_version_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_version_types.go
  apis/kubedb/v1alpha1/etcd_version_helpers.go
  apis/kubedb/v1alpha1/etcd_version_types.go
  apis/kubedb/v1alpha1/memcached_version_helpers.go
  apis/kubedb/v1alpha1/memcached_version_types.go
  apis/kubedb/v1alpha1/mongodb_version_helpers.go
  apis/kubedb/v1alpha1/mongodb_version_types.go
  apis/kubedb/v1alpha1/mysql_version_helpers.go
  apis/kubedb/v1alpha1/mysql_version_types.go
  apis/kubedb/v1alpha1/openapi_generated.go
  apis/kubedb/v1alpha1/redis_version_helpers.go
  apis/kubedb/v1alpha1/redis_version_types.go
  apis/kubedb/v1alpha1/register.go
  apis/kubedb/v1alpha1/zz_generated.deepcopy.go
  client/clientset/versioned/typed/kubedb/v1alpha1/elasticsearchversion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/etcdversion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/fake/fake_elasticsearchversion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/fake/fake_etcdversion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/fake/fake_kubedb_client.go
  client/clientset/versioned/typed/kubedb/v1alpha1/fake/fake_memcachedversion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/fake/fake_mongodbversion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/fake/fake_mysqlversion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/fake/fake_redisversion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/generated_expansion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/kubedb_client.go
  client/clientset/versioned/typed/kubedb/v1alpha1/memcachedversion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/mongodbversion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/mysqlversion.go
  client/clientset/versioned/typed/kubedb/v1alpha1/redisversion.go
  client/informers/externalversions/generic.go
  client/informers/externalversions/kubedb/v1alpha1/elasticsearchversion.go
  client/informers/externalversions/kubedb/v1alpha1/etcdversion.go
  client/informers/externalversions/kubedb/v1alpha1/interface.go
  client/informers/externalversions/kubedb/v1alpha1/memcachedversion.go
  client/informers/externalversions/kubedb/v1alpha1/mongodbversion.go
  client/informers/externalversions/kubedb/v1alpha1/mysqlversion.go
  client/informers/externalversions/kubedb/v1alpha1/redisversion.go
  client/listers/kubedb/v1alpha1/elasticsearchversion.go
  client/listers/kubedb/v1alpha1/etcdversion.go
  client/listers/kubedb/v1alpha1/expansion_generated.go
  client/listers/kubedb/v1alpha1/memcachedversion.go
  client/listers/kubedb/v1alpha1/mongodbversion.go
  client/listers/kubedb/v1alpha1/mysqlversion.go
  client/listers/kubedb/v1alpha1/redisversion.go
  hack/gencrd/main.go
Labels: in progress

#258 Fix error checking
  client/clientset/versioned/typed/kubedb/v1alpha1/util/dormant_database.go
  client/clientset/versioned/typed/kubedb/v1alpha1/util/elasticsearch.go
  client/clientset/versioned/typed/kubedb/v1alpha1/util/etcd.go
  client/clientset/versioned/typed/kubedb/v1alpha1/util/memcached.go
  client/clientset/versioned/typed/kubedb/v1alpha1/util/mongodb.go
  client/clientset/versioned/typed/kubedb/v1alpha1/util/mysql.go
  client/clientset/versioned/typed/kubedb/v1alpha1/util/postgres.go
  client/clientset/versioned/typed/kubedb/v1alpha1/util/redis.go
  client/clientset/versioned/typed/kubedb/v1alpha1/util/snapshot.go
Labels: in progress

#259 GetKind from kutil
  pkg/controller/snapshot/cron.go
Labels: in progress

#260 Enable status sub resource for crd yamls
  api/crds/dormantdatabase.yaml
  api/crds/elasticsearch.yaml
  api/crds/memcached.yaml
  api/crds/mongodb.yaml
  api/crds/postgres.yaml
  api/crds/redis.yaml
  api/crds/snapshot.yaml
  hack/gencrd/main.go
Labels: in progress

#261 Remove regex restriction on db version crds
  api/crds/elasticsearchversion.yaml
  api/crds/memcachedversion.yaml
  api/crds/mongodbversion.yaml
  api/crds/mysqlversion.yaml
  api/crds/postgresversion.yaml
  api/crds/redisversion.yaml
  apis/kubedb/v1alpha1/elasticsearch_version_helpers.go
  apis/kubedb/v1alpha1/etcd_version_helpers.go
  apis/kubedb/v1alpha1/memcached_version_helpers.go
  apis/kubedb/v1alpha1/mongodb_version_helpers.go
  apis/kubedb/v1alpha1/mysql_version_helpers.go
  apis/kubedb/v1alpha1/postgres_version_helpers.go
  apis/kubedb/v1alpha1/redis_version_helpers.go
Labels: bug, in progress

#262 Rename OffshootLabels to OffshootSelectors
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/redis_helpers.go
Labels: in progress

#263 Rename StatefulSetLabels to OffshootLabels
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/helpers.go
  apis/kubedb/v1alpha1/helpers_test.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/redis_helpers.go
Labels: in progress

#264 Add OffshootLabels for Snaphsots
  apis/kubedb/v1alpha1/snapshot_helpers.go
Labels: in progress

#267 Take 'AnnotationJobType' from labels
  pkg/controller/job/job.go
Labels: bug

#268 Implemented StatsAccessor interface with another struct
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/openapi_generated.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/redis_helpers.go
Labels: in progress

#269 Fix return value from filterTags
  apis/kubedb/v1alpha1/helpers.go
Labels: in progress

#270 Fix self-loop of statsService GetNamespace method
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/redis_helpers.go
Labels: in progress

#274 Support categories in CRDs
  api/crds/dormantdatabase.yaml
  api/crds/elasticsearch.yaml
  api/crds/elasticsearchversion.yaml
  api/crds/memcached.yaml
  api/crds/memcachedversion.yaml
  api/crds/mongodb.yaml
  api/crds/mongodbversion.yaml
  api/crds/mysql.yaml
  api/crds/mysqlversion.yaml
  api/crds/postgres.yaml
  api/crds/postgresversion.yaml
  api/crds/redis.yaml
  api/crds/redisversion.yaml
  api/crds/snapshot.yaml
  apis/kubedb/v1alpha1/dormant_database_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_version_helpers.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/etcd_version_helpers.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/memcached_version_helpers.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mongodb_version_helpers.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/mysql_version_helpers.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/postgres_version_helpers.go
  apis/kubedb/v1alpha1/redis_helpers.go
  apis/kubedb/v1alpha1/redis_version_helpers.go
  apis/kubedb/v1alpha1/snapshot_helpers.go
  glide.lock
  vendor/github.com/appscode/kutil/apiextensions/v1beta1/cli-utils.go
  vendor/github.com/appscode/kutil/core/v1/kubernetes.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_linux.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: in progress

#275 Migrate deprecated crd fields to PodTemplate
  apis/kubedb/v1alpha1/dormant_database_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/helpers.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/redis_helpers.go
  apis/kubedb/v1alpha1/snapshot_helpers.go
  apis/kubedb/v1alpha1/snapshot_types.go
  apis/kubedb/v1alpha1/zz_generated.deepcopy.go
Labels: in progress

#276 Don't check bucket access in webhook
  pkg/admission/snapshot/admission.go
  pkg/controller/snapshot/snapshot.go
  pkg/validator/validate.go
Labels: in progress

#278 Added helper function 'Equal' to compare new and old objects
  apis/kubedb/v1alpha1/dormant_database_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/redis_helpers.go
  apis/kubedb/v1alpha1/snapshot_helpers.go
  pkg/controller/dormantdatabase/workqueue.go
Labels: in progress

#279 Rename Equal method to AlreadyObserved
  apis/kubedb/v1alpha1/dormant_database_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/redis_helpers.go
  apis/kubedb/v1alpha1/snapshot_helpers.go
  pkg/controller/dormantdatabase/workqueue.go
Labels: in progress

#280 Update Redis.AlreadyObserved method
  apis/kubedb/v1alpha1/dormant_database_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/redis_helpers.go
  apis/kubedb/v1alpha1/snapshot_helpers.go
Labels: in progress

#282 Use EqualAnnotation
  apis/kubedb/v1alpha1/dormant_database_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/redis_helpers.go
  apis/kubedb/v1alpha1/snapshot_helpers.go
  glide.lock
  vendor/github.com/appscode/kutil/meta/cmp.go
  vendor/github.com/graymeta/stow/azure/container.go
  vendor/github.com/graymeta/stow/google/container.go
  vendor/github.com/graymeta/stow/local/container.go
  vendor/github.com/graymeta/stow/s3/container.go
  vendor/github.com/graymeta/stow/stow.go
  vendor/github.com/graymeta/stow/swift/container.go
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_linux.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/kmodules.xyz/objectstore-api/osm/osm.go
Labels: in progress

#283 Add `all` to crd categories
  api/crds/dormantdatabase.yaml
  api/crds/elasticsearch.yaml
  api/crds/elasticsearchversion.yaml
  api/crds/memcached.yaml
  api/crds/memcachedversion.yaml
  api/crds/mongodb.yaml
  api/crds/mongodbversion.yaml
  api/crds/mysql.yaml
  api/crds/mysqlversion.yaml
  api/crds/postgres.yaml
  api/crds/postgresversion.yaml
  api/crds/redis.yaml
  api/crds/redisversion.yaml
  api/crds/snapshot.yaml
  apis/kubedb/v1alpha1/dormant_database_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_version_helpers.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/etcd_version_helpers.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/memcached_version_helpers.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mongodb_version_helpers.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/mysql_version_helpers.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/postgres_version_helpers.go
  apis/kubedb/v1alpha1/redis_helpers.go
  apis/kubedb/v1alpha1/redis_version_helpers.go
  apis/kubedb/v1alpha1/snapshot_helpers.go
Labels: in progress

#285 Fix skip bucket access verification for local volume
  pkg/controller/snapshot/snapshot.go
Labels: in progress

#286 Introduce storageType : ephemeral
  api/crds/elasticsearch.yaml
  api/crds/mongodb.yaml
  api/crds/mysql.yaml
  api/crds/postgres.yaml
  api/crds/redis.yaml
  api/openapi-spec/swagger.json
  apis/kubedb/v1alpha1/elasticsearch_types.go
  apis/kubedb/v1alpha1/etcd_types.go
  apis/kubedb/v1alpha1/mongodb_types.go
  apis/kubedb/v1alpha1/mysql_types.go
  apis/kubedb/v1alpha1/openapi_generated.go
  apis/kubedb/v1alpha1/postgres_types.go
  apis/kubedb/v1alpha1/redis_types.go
  apis/kubedb/v1alpha1/types.go
  apis/kubedb/v1alpha1/zz_generated.deepcopy.go
  pkg/validator/validate.go
Labels: in progress

#287 Check that spec.storage is unset for ephemeral storage type
  pkg/validator/validate.go
Labels: in progress

#288 Require spec.storage field for durable storage type
  pkg/validator/validate.go
Labels: in progress

#289 Support passing args via PodTemplate
  glide.lock
  pkg/admission/dormantdatabase/admission.go
  pkg/admission/snapshot/admission.go
  pkg/admission/snapshot/admission_test.go
  vendor/kmodules.xyz/offshoot-api/api/v1/openapi_generated.go
  vendor/kmodules.xyz/offshoot-api/api/v1/types.go
  vendor/kmodules.xyz/offshoot-api/api/v1/zz_generated.deepcopy.go
Labels: in progress

#290 Regenerate crd yamls
  api/crds/elasticsearch.yaml
  api/crds/memcached.yaml
  api/crds/mongodb.yaml
  api/crds/mysql.yaml
  api/crds/postgres.yaml
  api/crds/redis.yaml
  api/crds/snapshot.yaml
  api/openapi-spec/swagger.json
  apis/kubedb/v1alpha1/openapi_generated.go
Labels: in progress

#291 Use EtcdVersion for Etcd images
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/etcd_version_types.go
  apis/kubedb/v1alpha1/openapi_generated.go
  apis/kubedb/v1alpha1/zz_generated.deepcopy.go
Labels: in progress

#292 Mark version field as reuiqred
  api/crds/elasticsearchversion.yaml
  api/crds/memcachedversion.yaml
  api/crds/mongodbversion.yaml
  api/crds/mysqlversion.yaml
  api/crds/postgresversion.yaml
  api/crds/redisversion.yaml
  api/openapi-spec/swagger.json
  apis/kubedb/v1alpha1/elasticsearch_version_types.go
  apis/kubedb/v1alpha1/etcd_version_types.go
  apis/kubedb/v1alpha1/memcached_version_types.go
  apis/kubedb/v1alpha1/mongodb_version_types.go
  apis/kubedb/v1alpha1/mysql_version_types.go
  apis/kubedb/v1alpha1/openapi_generated.go
  apis/kubedb/v1alpha1/postgres_version_types.go
  apis/kubedb/v1alpha1/redis_version_types.go
Labels: in progress

#293 Add status.observedGenerationHash
  api/crds/elasticsearch.yaml
  api/crds/memcached.yaml
  api/crds/mongodb.yaml
  api/crds/mysql.yaml
  api/crds/postgres.yaml
  api/crds/redis.yaml
  api/crds/snapshot.yaml
  api/openapi-spec/swagger.json
  apis/kubedb/v1alpha1/dormant_database_helpers.go
  apis/kubedb/v1alpha1/dormant_database_types.go
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
  apis/kubedb/v1alpha1/elasticsearch_types.go
  apis/kubedb/v1alpha1/etcd_helpers.go
  apis/kubedb/v1alpha1/etcd_types.go
  apis/kubedb/v1alpha1/memcached_helpers.go
  apis/kubedb/v1alpha1/memcached_types.go
  apis/kubedb/v1alpha1/mongodb_helpers.go
  apis/kubedb/v1alpha1/mongodb_types.go
  apis/kubedb/v1alpha1/mysql_helpers.go
  apis/kubedb/v1alpha1/mysql_types.go
  apis/kubedb/v1alpha1/openapi_generated.go
  apis/kubedb/v1alpha1/postgres_helpers.go
  apis/kubedb/v1alpha1/postgres_types.go
  apis/kubedb/v1alpha1/redis_helpers.go
  apis/kubedb/v1alpha1/redis_types.go
  apis/kubedb/v1alpha1/snapshot_helpers.go
  apis/kubedb/v1alpha1/snapshot_types.go
  glide.lock
  pkg/controller/dormantdatabase/dormant_database.go
  pkg/controller/dormantdatabase/workqueue.go
  vendor/github.com/appscode/kutil/meta/arguments.go
  vendor/github.com/appscode/kutil/meta/hash.go
  vendor/github.com/appscode/kutil/tools/queue/handler.go
  vendor/github.com/fatih/structs/LICENSE
  vendor/github.com/fatih/structs/field.go
  vendor/github.com/fatih/structs/structs.go
  vendor/github.com/fatih/structs/tags.go
  vendor/github.com/go-openapi/spec/bindata.go
  vendor/github.com/go-openapi/spec/debug.go
  vendor/github.com/go-openapi/spec/expander.go
  vendor/github.com/go-openapi/spec/header.go
  vendor/github.com/go-openapi/spec/info.go
  vendor/github.com/go-openapi/spec/items.go
  vendor/github.com/go-openapi/spec/operation.go
  vendor/github.com/go-openapi/spec/parameter.go
  vendor/github.com/go-openapi/spec/path_item.go
  vendor/github.com/go-openapi/spec/response.go
  vendor/github.com/go-openapi/spec/responses.go
  vendor/github.com/go-openapi/spec/schema.go
  vendor/github.com/go-openapi/spec/security_scheme.go
  vendor/github.com/go-openapi/spec/swagger.go
  vendor/github.com/go-openapi/spec/tag.go
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/ncw/swift/swift.go
Labels: in progress

#294 Add OffshootSelectors to DormantDatabase
  apis/kubedb/v1alpha1/dormant_database_helpers.go
Labels: in progress

#295 Add Kind() method
  apis/kubedb/v1alpha1/register.go
Labels: in progress

#297 Elasticsearch: Don't return http/https from Scheme function
  apis/kubedb/v1alpha1/elasticsearch_helpers.go
Labels: in progress
